export const products = [
    {
        title: 'Aluminum rafters for patio roofing or patio roofing',
        imageUrl: '/images/product-section/img-product-alum.png',
        altText: 'Aluminum rafters',
        price: '35.95€',
        link: '/product/aluminum1',
        category: 'alu-zaun',
        slug: '1',
        inStock: true,
        roofType: 'vsg',
    },
    {
        title: 'Aluminum rafters for patio roofing',
        imageUrl: '/images/product-section/img-product-alum.png',
        altText: 'Aluminum rafters',
        price: '6.50€',
        oldPrice: '7.50€',
        link: '/product/aluminum2',
        category: 'alu-zaun',
        slug: '2',
        inStock: true,
        roofType: 'polycarbonat',
    },
    {
        title: 'Aluminum rafters for patio roofing or patio roofing',
        imageUrl: '/images/product-section/img-product-alum.png',
        altText: 'Aluminum rafters',
        price: '15.95€',
        link: '/product/aluminum3',
        category: 'alu-zaun',
        slug: '3',
        inStock: true,
        roofType: 'vsg',
    },
    {
        title: 'Aluminum rafters for patio roofing or patio roofing',
        imageUrl: '/images/product-section/img-product-alum.png',
        altText: 'Aluminum rafters',
        price: '55.95€',
        link: '/product/aluminum4',
        category: 'alu-zaun',
        slug: '4',
        inStock: true,
        roofType: 'polycarbonat ',
    },
]
